# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad7cccd61065958765b187fb87f5dae4b04e5602bb8a7a015663653cfc29e2ef53a0dc125c51f413bdba08fe22ab5ea1fa812675d60f1e5bf0545364f4073511
  domain_name: 'gaaplogic.com'
  square_application_id: 'sandbox-sq0idp-AMzdqvzUmqHq7gpXvbw7ZQ'
  square_access_token: 'sandbox-sq0atb-aWaTagWOPgQ3vorUOGIhYQ'
  square_location_id: 'H6NS7804D5Q42'

test:
  secret_key_base: d6863a2c4c53bef32463a49e7363947e8663ff19bce4ab1593e64dd1ff27d514b12af7bd07a3215217e7861a400450febab429200730620cdc3fae8d40724102
  domain_name: 'gaaplogic.com'
  square_application_id: 'sandbox-sq0idp-AMzdqvzUmqHq7gpXvbw7ZQ'
  square_access_token: 'sandbox-sq0atb-aWaTagWOPgQ3vorUOGIhYQ'
  square_location_id: 'H6NS7804D5Q42'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV['DOMAIN_NAME'] %> 
  square_application_id: <%= ENV["SQUARE_APPLICATION_ID"] %>
  square_access_token: <%= ENV["SQUARE_ACCESS_TOKEN"] %>
  square_location_id: <%= ENV["SQUARE_LOCATION_ID"] %>
