# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b807706d07a3e9aa814341d6a87385ad04efd36132ea510fe3704aa2792485eb551ebc05c6ad1ac181d9140b3c3eb7a589de44d59a71ff106c78b7938664a519

test:
  secret_key_base: da97a65e2d25cd6c8b027e352a34d56d1da33d3337d6dd623d75bc2866c66a51b86849c5a4ea2252498211309b056abd2102bc873b86b1081ecd700ced398d45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
