# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# user = CreateAdminService.new.call
# puts 'CREATED ADMIN USER: ' << user.email

questions_array = 
  [
    Equity-linked transactions info node
Are you analyzing the entire instrument (or two or more agreements as though they are a single instrument), or are you analyzing a feature or provision embedded within an agreement?
Do you want to analyze the contract only with respect to derivative accounting guidance under ASC 815?
Is this a lease agreement?
Was this instrument issued as stock-based compensation to, and for goods and/or services provided by, an employee?
Was this instrument issued as stock-based compensation to, and for goods and/or services provided by, a nonemployee?
Does the instrument fall within the scope of ASC 480, Liabilities - Distinguishing Liabilities from Equity?
Does the contract meet the accounting definition of a derivative?
Are there any available exceptions that would preclude derivative accounting?
Is the instrument indexed to the company's own stock?
Is the contract for a business combination at a future date?
Is the contract for an acquisition entered into by a not-for-profit organization?
                                                           Is the contract for the merger of two or more not-for-profit organizations?
                                                                                                               Is the contract a forward contract that requires settlement by the company's delivery of cash in exchange for the purchase of a fixed number of its equity shares?
                                                                                                               Is the amount to be paid fixed or can the amount and/or settlement date vary?
                                                                                                               Classified in equity?
                                                                                                               Is the instrument indexed to the company's own stock?
                                                                                                               Does hedge accounting apply?
                                                                                                               Not a derivative and indexed to own stock
                                                                                                               Not a derivative and not indexed to own stock
                                                                                                               The contract to enter into a business combination at a future date is not subject to accounting as a derivative under ASC 815-20.  A more through treatment of business combinations will be undertaken by GAAP Logic in a future project.
                                                                                                                 The contract to enter into an acquisition by a nonprofit organization at a future date is not subject to accounting as a derivative under ASC 815-20.  A more through treatment of business combinations will be undertaken by GAAP Logic in a future project.
                                                                                                                 The contract to enter into a merger by a nonprofit organizations at a future date is not subject to accounting as a derivative under ASC 815-20.  A more through treatment of business combinations will be undertaken by GAAP Logic in a future project.
                                                                                                                 Account for the contract in accordance with ASC 480­10­30­3 through 30­5, 480­10­35­3, and 480­10­45­3. A more through treatment of ASC 480 will be undertaken by GAAP Logic in a future project.
                                                                                                                 Account for the contract in accordance with ASC 480­10­30­3 through 30­5, 480­10­35­3, and 480­10­45­3. A more through treatment of ASC 480 will be undertaken by GAAP Logic in a future project.
                                                                                                                 Derivative, not classified in equity
                                                                                                               Derivative, classified in equity, indexed to own stock
                                                                                                               Derivative, classified in equity, not indexed to own stock
                                                                                                               Apply hedge accounting in accordance with ASC 815. A more through treatment of hedge accounting will be undertaken by GAAP Logic in a future project.
                                                                                                                 Account for the contract as a freestanding derivative in accordance with ASC 815-20 recorded intially at fair value and subsequently remeasured at fair value. Any changes in fair value should be recoognized as gain or loss in income.

                                                                                                                 Is the contract a registration payments arrangement?
                                                                                                               Is the contract for a business combination at a future date?
                                                                                                               Is the contract for an acquisition entered into by a non-for-profit organization?
                                                                                                                                                                          Is the contract for the merger of two or more not-for-profit organizations?
                                                                                                                                                                                                                              Is the contract a forward contract that requires settlement by the company's delivery of cash in exchange for the purchase of a fixed number of its equity shares?
                                                                                                                                                                                                                              Is the amount to be paid fixed or can the amount and/or settlement date vary?
                                                                                                                                                                                                                              Does the contract meet the accounting definition of a derivative?
                                                                                                                                                                                                                              Does hedge accounting apply?
                                                                                                                                                                                                                              Is the host contract of the embedded feature being evaluated considered conventional convertible debt?
                                                                                                                                                                                                                              Does the conversion feature meet the accounting definition of a derivative?
                                                                                                                                                                                                                              Is the embedded feature a conversion option in a debt-host contract?
                                                                                                                                                                                                                              Is there a beneficial conversion feature as of the date of issuance?
                                                                                                                                                                                                                              Upon conversion may the entire convertible debt instrument be entirely or partially settled in cash or by transfer of some other asset?
                                                                                                                                                                                                                              The lease contract should be accounted for under ASC 840, Leases. A more thorough treatment of ASC 840 will be undertaken by GAAP Logic in a future project. It is not uncommon, however, for a lease to contain one or more provisions that meet the accounting definition of a derivitive and require separate accounting as an embedded derivative. Since the lease is linked to the company's equity, those provisions should be specifically evaluated as an embedded derivative feature.
                                                                                                                                                                                                                              Stock compensation paid to an employee should be accounted for in accordance eith ASC 718, Compensation--Stock Compensation
                                                                                                                                                                                                                              Stock compensation paid to a nonemployee for goods and/or services becomes subject to evauluation under ASC 815-10 once performance has occurred. Since the equity-linked contract meets the accounting definition of a derivative, the contract should be accounted for as a freestanding derivative initially recorded at fair value and subsequently remeasured at fair value. Any changes in fair value should be recoognized as gain or loss in income.
                                                                                                                                                                                                                                Stock compensation paid to a nonemployee for goods and/or services becomes subject to evauluation under ASC 815-10 once performance has occurred. However, since the equity-linked contract does not meet the accounting definition of a derivative, the contract should be recorded at fair value in accordance with ASC 505-50 and should not be subsequently remeasured.
                                                                                                                                                                                                                                Stock compensation paid to a nonemployee for which the products and/or services have not been provided should be accounted for in accordance with ASC 505-50, Equity-Based Payments to Nonemployees.

                                                                                                                                                                                                                                Is the company the issuer or the provider of the goods and/or services?
                                                                                                                                                                                                                              Have the goods and/or services of the non-employee already been provided?
                                                                                                                                                                                                                              Pass - goods and/or services have not been provided
                                                                                                                                                                                                                              Stock compensation paid to an employee should be accounted for in accordance eith ASC 718, Compensation--Stock Compensation
                                                                                                                                                                                                                              Stock compensation paid to a nonemployee for goods and/or services becomes subject to evauluation under ASC 815-10 once performance has occurred. Since the equity-linked contract meets the accounting definition of a derivative, the contract should be accounted for as a freestanding derivative initially recorded at fair value and subsequently remeasured at fair value. Any changes in fair value should be recoognized as gain or loss in income.
                                                                                                                                                                                                                                Stock compensation paid to a nonemployee for goods and/or services becomes subject to evauluation under ASC 815-10 once performance has occurred. However, since the equity-linked contract does not meet the accounting definition of a derivative, the contract should be recorded at fair value in accordance with ASC 505-50 and should not be subsequently remeasured.
                                                                                                                                                                                                                                Stock compensation paid to a nonemployee for which the products and/or services have not been provided should be accounted for in accordance with ASC 505-50, Equity-Based Payments to Nonemployees.

                                                                                                                                                                                                                                The lease contract should be accounted for under ASC 840, Leases. A more thorough treatment of ASC 840 will be undertaken by GAAP Logic in a future project. It is not uncommon, however, for a lease to contain one or more provisions that meet the accounting definition of a derivitive and require separate accounting as an embedded derivative. Since the lease is linked to the company's equity, those provisions should be specifically evaluated as an embedded derivative feature.















                                                                                                                                                                                                                                Is this a mandatorily redeemable financial instrument (e.g., mandatorily redeemable preferred stock)?
                                                                                                                                                                                                                                Is this instrument an obligation to repurchase the companys shares for cash or by transferring some other asset to the counterparty?
                                                                                                                                                                                                                              Is this an obligation to issue to the holder a variable number of shares based on a fixed monetary amount known at inception of the instrument?
                                                                                                                                                                                                                              Is this an obligation to issue to the holder a variable number of shares based on variations on something other than the fair value of the entity's own stock?
                                                                                                                                                                                                                              Is this an obligation to issue to the holder a variable number of shares based on variations inversely related to changes in the fair value of the entitys own stock?
                                                                                                                                                                                                                              Account for the contract in accordance with ASC 480, Distingushing Liabilities from Equity. A more through treatment of ASC 480 will be undertaken by GAAP Logic in a future project.

                                                                                                                                                                                                                                Does the contract require that the issuer file a registration statement for the resale of specified financial instruments and/or for the resale of equity shares of the financial instrument that are issuable upon exercise or conversion of specified financial instruments?
                                                                                                                                                                                                                              Does the contract require that the registration statement be declared effective by the SEC within a specified time period?
                                                                                                                                                                                                                              Does the contract require that the effectiveness of the registration statement be maintained a specified time period?
                                                                                                                                                                                                                              Pass - Has at least one of the conditions
                                                                                                                                                                                                                              Does the contract require the issuer to transfer consideration if the effectiveness of the registration statement is not declared or if the effectiveness of the registration statement is not maintained?
                                                                                                                                                                                                                              Pass - Meets the condition
                                                                                                                                                                                                                              Pass - Meets both conditions
                                                                                                                                                                                                                              Is the insrument that is the subject of the registration payments arrangement convertible debt or convertible preferred stock?
                                                                                                                                                                                                                              Is the form of consideration payable to the counterparty an adjustment to the conversion ratio?
                                                                                                                                                                                                                              Is the consideration payable to the counterparty determined by reference to an observable market other than the market for the company's stock?
                                                                                                                                                                                                                              Is the consideration payable to the counterparty determined by reference to an observable index?
                                                                                                                                                                                                                              Pass - neither condition is present
                                                                                                                                                                                                                              Does payment of consideration under the registration payments arrangement settle the instrument(s) subject to the arrangement?
                                                                                                                                                                                                                              A convertible instrument with a contingently adjustable conversion ratio should be accounted for in accordance with ASC 470-20, Debt with Conversion and Other Options. A more through treatment of debt in general under ASC 470 will be undertaken by GAAP Logic in a future project.
                                                                                                                                                                                                                              A registration payament arrangement whose payment is determined by reference to 1) am observable market other than the market for the company's stock and/or 2) an observable index should accounted for as a derivative in accordance with ASC 815-10. Record the contract initially at fair value and remeasure subsequently at fair value at each reporting date.  Any changes in fair value should be recoognized as gain or loss in income.
                                                                                                                                                                                                                              A registration payment arrangement whose consideration payment settles the instrument(s) subject to the arrangement should be accounted for as a contingent liability.
                                                                                                                                                                                                                              A registration payment arrangement should be accounted for in accordance with ASC 825-20--Registration Payment Arrangements.

                                                                                                                                                                                                                              Is there 1) one or more underlyings, and 2) a notional amount, a payment provision, or both?
                                                                                                                                                                                                                              Is there one or more underlyings?
                                                                                                                                                                                                                              Is there a notional amount?
                                                                                                                                                                                                                              Do the underlying (or one of the underlyings) and the notional amount interact to determine the amount of the settlement of the contract? 
                                                                                                                                                                                                                              Is there a payment provision?
                                                                                                                                                                                                                              Is the payment provision triggered by the underlying (or one or more of the underlyings)?
                                                                                                                                                                                                                                Pass - Meets first condition
                                                                                                                                                                                                                                Is there a low or no initial investment?
                                                                                                                                                                                                                              Does the contract require a payment that is equal to the notional amount (plus a premium or minus a discount)?
                                                                                                                                                                                                                                Is the contract's initial net investment less, by more than a nominal amount, than the initial investment that would be required to either buy the asset related to the underlying or incur the obligation related to the underlying?
                                                                                                                                                                                                                              Pass - Meets second condition condition
                                                                                                                                                                                                                              Is there net settlement either by the terms of the contract, through a market mechanism or by delivery of a derivative instrument or asset that is readily convertible to cash?
                                                                                                                                                                                                                              Is there net settlement of the contract under its terms?
                                                                                                                                                                                                                              Is either party to the contract required to deliver an asset that is associated with the underlying and that has a principal amount, stated amount, face value, number of shares, or other denomination that is equal to the notional amount (or the notional plus a premium or minus a discount)?
                                                                                                                                                                                                                                Does the contract require or permit either or both parties to net share settle the contract?
                                                                                                                                                                                                                              Does the contract contain a penalty for nonperformance based on changes in the price of the items that are the subject of the contract?
                                                                                                                                                                                                                              Does the contract contain an incremental fixed penalty or fixed amount per unit?
                                                                                                                                                                                                                              Is the amount of the fixed penalty considered significant enough at all times during the term of the contract to make the possibility of nonperformance remote?
                                                                                                                                                                                                                              Does the contract provide for a structured payout over time of gain or loss resulting from the contract?
                                                                                                                                                                                                                              Is the fair value of the cash flows to received (or paid) by the holder under the structured payout approximately equal to the amount that would have been received (or paid) under immediate payout?
                                                                                                                                                                                                                              Does the contract require additional investing or borrowing to obtain the benefits pf the contract's gain?
                                                                                                                                                                                                                              Is the additional investing or borrowing a nontraditional adjustment of the yield on the amount invested or the interest element on the amount borrowed?
                                                                                                                                                                                                                              Is the contract a debt instrument?
                                                                                                                                                                                                                              Does the contract contain an embedded put or call option?
                                                                                                                                                                                                                              If a call option, is the holder the debtor?
                                                                                                                                                                                                                              If a put option, is the issuer the debtor?
                                                                                                                                                                                                                              Pass - meets conditions for net settlement by terms of the contract
                                                                                                                                                                                                                              Is there net settlement available by means of a market mechanism?
                                                                                                                                                                                                                              Is there a means for one or both parties to liquidate its net position through a net payment?
                                                                                                                                                                                                                              Does liquidating the net position result in that party being fully relieved of it rights and obligations under the contract?
                                                                                                                                                                                                                              Does liquidation of the net position require significant transaction costs?
                                                                                                                                                                                                                              Does liquidation of the net position occur without significant negotiation and due diligence?
                                                                                                                                                                                                                              Does liquidation of the net position occur within a time frame that is considered customary for this type of contract?
                                                                                                                                                                                                                              Pass - meets conditions for net settlement through market mechanism
                                                                                                                                                                                                                              Is there net settlement by delivery of a derivative instrument or by delivery of an asset that is readily convertible to cash?
                                                                                                                                                                                                                              Is the contract a stock purchase warrants or stock purchase option?
                                                                                                                                                                                                                              Is the stock underlying the warrant (or option) publicly traded?
                                                                                                                                                                                                                              Is the  warrant (or option) only for shares of the issuer (or that of its consolidated subsidieries?
                                                                                                                                                                                                                                                                                         Is sale or transfer of the shares issuable upon exercise restricted for a period of 32 days or more from the date of exercise?
                                                                                                                                                                                                                                                                                         Does the holder have the power, contractually or by other means, to cause the restriction to be met within 31 days of the date of exercise?
                                                                                                                                                                                                                                                                                         Is the asset underlying the contract publicly traded stock?
                                                                                                                                                                                                                                                                                         Can the active market rapidaly absorb the quantity of stock to be received upon exercise without significantly affecting the price?
                                                                                                                                                                                                                                                                                         Are the estimated costs to convert the stock to cash considered to be significant?
                                                                                                                                                                                                                                                                                         Is the asset deliverable upon settlement of the contract readily convertible to cash?
                                                                                                                                                                                                                                                                                         Is the amount of cash that would be received from sale of the asset on an active market, net of transaction costs, approximately equal to what the entity would have received under a net settlement provision?
                                                                                                                                                                                                                                                                                         Pass - meets conditions for net settlement by readily convertible to cash
                                                                                                                                                                                                                                                                                         Pass - meets third condition
                                                                                                                                                                                                                                                                                         Pass - Meets definition of a derivative

                                                                                                                                                                                                                                                                                         Is the instrument's exercise contingent?
                                                                                                                                                                                                                                                                                         Is the contingency based on a) an observable market, other than the market for the issuer's stock, or b) an observable index, other than one measured solely by reference to the issuer''s own operations?
                                                                                                                                                                                                                                                                                         Is the settlement amount equal to the difference between the fair value of a fixed number of the entity's shares and a) a fixed monetary amount or b) a fixed amount of debt issued by the entity?
                                                                                                                                                                                                                                                                                         Pass - indexed to own stock

                                                                                                                                                                                                                                                                                         Does the contract require net cash settlement?
                                                                                                                                                                                                                                                                                         Does the contract require physical settlement or net share settlement?
                                                                                                                                                                                                                                                                                         Does the contract provide the counterparty with the choice of net cash settlement or settlement in shares?
                                                                                                                                                                                                                                                                                         Is the economic value of the share settlement alternative greater than that of the net cash settlement alternative, or is the cash settlement alternative fixed or does it contain a cap or floor?
                                                                                                                                                                                                                                                                                         Does the substance of the transaction in any way overcome the assumption of net cash settlement when the counterparty has the choice of net cash settlement or share settlement?
                                                                                                                                                                                                                                                                                         Does the contract provide the company with the choice of net cash settlement or settlement in shares?
                                                                                                                                                                                                                                                                                         Is the economic value of the share settlement alternative greater than that of the cash settlement alternative, or is the cash settlement alternative fixed or does it contain a cap or floor?
                                                                                                                                                                                                                                                                                         Does the substance of the transaction in any way overcome the assumption of share settlement when the entity has the choice of net cash settlement or share settlement?
                                                                                                                                                                                                                                                                                         Does the contract permit the entity to settle in unregistered shares?
                                                                                                                                                                                                                                                                                         Does the entity have sufficient authorized and unissued shares available to settle the contract after considering all other commitments that may require the issuance of stock during the maximum period the derivative contract could remain outstanding?
                                                                                                                                                                                                                                                                                         Does the contract contain an explicit limit on the number of shares to be delivered in a share settlement?
                                                                                                                                                                                                                                                                                         Are there any required cash payments to the counterparty in the event the company fails to make timely filings with the SEC?
                                                                                                                                                                                                                                                                                         Are there any required cash payments to the counterparty if the shares initially delivered upon settlement are subsequently sold by the counterparty and the sales proceeds are insufficient to provide the counterparty with full return of the amount due?
                                                                                                                                                                                                                                                                                         If the contract provides for net-cash settlement, is net-cash settlement required only in specific circumstances in which holders of shares underlying the contract also would receive cash in exchange for their shares?
                                                                                                                                                                                                                                                                                         Are there any provisions in the contract that indicate that the counterparty has rights that rank higher than those of a shareholder of the stock underlying the contract?
                                                                                                                                                                                                                                                                                         Is there a requirement in the contract to post collateral at any point or for any reason?
                                                                                                                                                                                                                                                                                         Pass - meets criteria for classified in equity
                                                                                                                                                                                                                                                                                         A derivative contract linked to the company's own stock that requires net cash settlement should not be classified in equity. Recognize the contract as a freestanding derivative recorded intially at fair value and subsequently remeasured at fair value. Any changes in fair value should be recoognized as gain or loss in income.

                                                                                                                                                                                                                                                                                           Is the host contract of the embedded feature being evaluated considered conventional convertible debt?
                                                                                                                                                                                                                                                                                         Is there a beneficial conversion feature as of the date of issuance?
                                                                                                                                                                                                                                                                                         Upon conversion may the entire convertible debt instrument be entirely or partially settled in cash or by transfer of some other asset?
                                                                                                                                                                                                                                                                                         Does the contract meet the accounting definition of a derivative?
                                                                                                                                                                                                                                                                                         Are there exceptions?
                                                                                                                                                                                                                                                                                         Are the economic risks and characteristics of the embedded feature clearly and closely related to the economic risks and characteristics of the host contract?
                                                                                                                                                                                                                                                                                         Is the embedded feature a conversion option in a debt-host contract?
                                                                                                                                                                                                                                                                                         Is there a beneficial conversion feature as of the date of issuance?
                                                                                                                                                                                                                                                                                         Upon conversion may the entire convertible debt instrument be entirely or partially settled in cash or by transfer of some other asset?
                                                                                                                                                                                                                                                                                         Classified in equity?
                                                                                                                                                                                                                                                                                         Is the instrument indexed to the company's own stock?
                                                                                                                                                                                                                                                                                         The embedded feature does not meet the accounting definition of a derivative. Do no bifurcate the embedded feature for accounting purposes.
                                                                                                                                                                                                                                                                                           Account for the instrument as conventional debt. A more through treatment of debt will be undertaken by GAAP Logic in a future project.
                                                                                                                                                                                                                                                                                           Account for the liability and equity components separately in accordance with the Cash Conversion subsections ASC 470-20. A more through treatment of debt will be undertaken by GAAP Logic in a future project.
                                                                                                                                                                                                                                                                                           Account for the debt and the beneficial conversion feature separately in accordance with ASC 470-20. A more through treatment of debt will be undertaken by GAAP Logic in a future project.
                                                                                                                                                                                                                                                                                           The embedded feature does not meet the accounting definition of a derivative. Do no bifurcate the embedded feature for accounting purposes.
                                                                                                                                                                                                                                                                                           Meets definition of a derivative but there are available exceptions
                                                                                                                                                                                                                                                                                           Meets definition of a derivative, not indexed to own stock
                                                                                                                                                                                                                                                                                           Meets definition of a derivative, indexed to own stock, not classified in equity
                                                                                                                                                                                                                                                                                           Meets definition of a derivative, indexed to own stock, classified in equity

                                                                                                                                                                                                                                                                                           Does the conversion provision provide the holder the option to convert into only a fixed number of shares or the equivalent amount of cash (at the discretion of the issuer)?
                                                                                                                                                                                                                                                                                           Is the ability to exercise the option based solely on the passage of time or a contingent event?
                                                                                                                                                                                                                                                                                         Does the conversion provision include adjustments to the number of shares issuable upon conversion?
                                                                                                                                                                                                                                                                                         Are the adjustments solely standard antidilution provisions?
                                                                                                                                                                                                                                                                                         Pass - meets definition of conventional convertible debt

                                                                                                                                                                                                                                                                                         Is there a beneficial conversion feature as of the date of issuance?
                                                                                                                                                                                                                                                                                         Upon conversion may the entire convertible debt instrument be entirely or partially settled in cash or by transfer of some other asset?
                                                                                                                                                                                                                                                                                         Account for the instrument as conventional debt. A more through treatment of debt will be undertaken by GAAP Logic in a future project.
                                                                                                                                                                                                                                                                                           Account for the liability and equity components separately in accordance with the Cash Conversion subsections ASC 470-20. A more through treatment of debt will be undertaken by GAAP Logic in a future project.
                                                                                                                                                                                                                                                                                           Account for the debt and the beneficial conversion feature separately in accordance with ASC 470-20. A more through treatment of debt will be undertaken by GAAP Logic in a future project.

                                                                                                                                                                                                                                                                                           Is there 1) one or more underlyings, and 2) a notional amount, a payment provision, or both?
                                                                                                                                                                                                                                                                                         Is there one or more underlyings?
                                                                                                                                                                                                                                                                                         Is there a notional amount?
                                                                                                                                                                                                                                                                                         Do the underlying (or one of the underlyings) and the notional amount interact to determine the amount of the settlement of the contract? 
                                                                                                                                                                                                                                                                                         Is there a payment provision?
                                                                                                                                                                                                                                                                                         Is the payment provision triggered by the underlying (or one or more of the underlyings)?
                                                                                                                                                                                                                                                                                           Pass - Meets first condition
                                                                                                                                                                                                                                                                                           Is there a low or no initial investment?
                                                                                                                                                                                                                                                                                         Does the contract require a payment that is equal to the notional amount (plus a premium or minus a discount)?
                                                                                                                                                                                                                                                                                           Is the contract's initial net investment less, by more than a nominal amount, than the initial investment that would be required to either buy the asset related to the underlying or incur the obligation related to the underlying?
                                                                                                                                                                                                                                                                                         Pass - Meets second condition condition
                                                                                                                                                                                                                                                                                         Is there net settlement either by the terms of the contract, through a market mechanism or by delivery of a derivative instrument or asset that is readily convertible to cash?
                                                                                                                                                                                                                                                                                         Is there net settlement of the contract under its terms?
                                                                                                                                                                                                                                                                                         Is either party to the contract required to deliver an asset that is associated with the underlying and that has a principal amount, stated amount, face value, number of shares, or other denomination that is equal to the notional amount (or the notional plus a premium or minus a discount)?
                                                                                                                                                                                                                                                                                           Does the contract require or permit either or both parties to net share settle the contract?
                                                                                                                                                                                                                                                                                         Does the contract contain a penalty for nonperformance based on changes in the price of the items that are the subject of the contract?
                                                                                                                                                                                                                                                                                         Does the contract contain an incremental fixed penalty or fixed amount per unit?
                                                                                                                                                                                                                                                                                         Is the amount of the fixed penalty considered significant enough at all times during the term of the contract to make the possibility of nonperformance remote?
                                                                                                                                                                                                                                                                                         Does the contract provide for a structured payout over time of gain or loss resulting from the contract?
                                                                                                                                                                                                                                                                                         Is the fair value of the cash flows to received (or paid) by the holder under the structured payout approximately equal to the amount that would have been received (or paid) under immediate payout?
                                                                                                                                                                                                                                                                                         Does the contract require additional investing or borrowing to obtain the benefits pf the contract's gain?
                                                                                                                                                                                                                                                                                         Is the additional investing or borrowing a nontraditional adjustment of the yield on the amount invested or the interest element on the amount borrowed?
                                                                                                                                                                                                                                                                                         Is the contract a debt instrument?
                                                                                                                                                                                                                                                                                         Does the contract contain an embedded put or call option?
                                                                                                                                                                                                                                                                                         If a call option, is the holder the debtor?
                                                                                                                                                                                                                                                                                         If a put option, is the issuer the debtor?
                                                                                                                                                                                                                                                                                         Pass - meets conditions for net settlement by terms of the contract
                                                                                                                                                                                                                                                                                         Is there net settlement available by means of a market mechanism?
                                                                                                                                                                                                                                                                                         Is there a means for one or both parties to liquidate its net position through a net payment?
                                                                                                                                                                                                                                                                                         Does liquidating the net position result in that party being fully relieved of it rights and obligations under the contract?
                                                                                                                                                                                                                                                                                         Does liquidation of the net position require significant transaction costs?
                                                                                                                                                                                                                                                                                         Does liquidation of the net position occur without significant negotiation and due diligence?
                                                                                                                                                                                                                                                                                         Does liquidation of the net position occur within a time frame that is considered customary for this type of contract?
                                                                                                                                                                                                                                                                                         Pass - meets conditions for net settlement through market mechanism
                                                                                                                                                                                                                                                                                         Is there net settlement by delivery of a derivative instrument or by delivery of an asset that is readily convertible to cash?
                                                                                                                                                                                                                                                                                         Is the contract a stock purchase warrants or stock purchase option?
                                                                                                                                                                                                                                                                                         Is the stock underlying the warrant (or option) publicly traded?
                                                                                                                                                                                                                                                                                         Is the  warrant (or option) only for shares of the issuer (or that of its consolidated subsidieries?
                                                                                                                                                                                                                                                                                                                                                    Is sale or transfer of the shares issuable upon exercise restricted for a period of 32 days or more from the date of exercise?
                                                                                                                                                                                                                                                                                                                                                    Does the holder have the power, contractually or by other means, to cause the restriction to be met within 31 days of the date of exercise?
                                                                                                                                                                                                                                                                                                                                                    Is the asset underlying the contract publicly traded stock?
                                                                                                                                                                                                                                                                                                                                                    Can the active market rapidaly absorb the quantity of stock to be received upon exercise without significantly affecting the price?
                                                                                                                                                                                                                                                                                                                                                    Are the estimated costs to convert the stock to cash considered to be significant?
                                                                                                                                                                                                                                                                                                                                                    Is the asset deliverable upon settlement of the contract readily convertible to cash?
                                                                                                                                                                                                                                                                                                                                                    Is the amount of cash that would be received from sale of the asset on an active market, net of transaction costs, approximately equal to what the entity would have received under a net settlement provision?
                                                                                                                                                                                                                                                                                                                                                    Pass - meets conditions for net settlement by readily convertible to cash
                                                                                                                                                                                                                                                                                                                                                    Pass - meets third condition
                                                                                                                                                                                                                                                                                                                                                    Pass - Meets definition of a derivative
  ]

questions_array.each do |q|
  puts q
  Question.find_or_create_by(
    question: q[:question],
    sort: q[:sort],
    module_code: '10',
    subject_id: q[:subject].to_f.round(0),
    kind: q[:type],
    question_code: q[:question_code]
  )
end
